### ISSUE TITLE
이미지 링크 오류

### ISSUE THREAD

**Issue by offetuoso** [gyoogle/tech-interview-for-developer#101]
본문에 추가된 이미지의 링크가 열리지가 않아 보이지 않네요 
감사합니다.

**Comment by offetuoso** [comment]
이미지 없는 해당 블로그 게시물 https://github.com/gyoogle/tech-interview-for-developer/blob/master/Linux/Von%20Neumann%20Architecture.md

**Comment by gyoogle** [comment]
감사합니다 수정완료했습니다:)
