### ISSUE TITLE
이미지 경로 변경에 따른 누락

### ISSUE THREAD

**Issue by MaetDol** [gyoogle/tech-interview-for-developer#104]
[Computer Science/Network/OSI 7 계층.md](https://github.com/gyoogle/tech-interview-for-developer/blob/9ca6c6adfbd2c1667c1b1f71381ed6c67fa7ad2f/Computer%20Science/Network/OSI%207%20%EA%B3%84%EC%B8%B5.md) 에서 7계층 이미지의 CDN 링크가 변경되어 404가 나옵니다.
[해당](https://s7280.pcdn.co/wp-content/uploads/2018/06/osi-model-7-layers-1.png) 링크로 변경된 것 같은데 맞는지 모르겠습니다. 필요하다면 풀리퀘 남기겠습니다!

양질의 정보글 잘 보고 있습니다. 감사합니다! ☺

**Comment by gyoogle** [comment]
감사합니다 :) PR 남겨주시면 적용하겠습니다!
