### ISSUE TITLE
JS오류에 대하여

### ISSUE THREAD

**Issue by ynifamily3** [gyoogle/tech-interview-for-developer#106]
https://github.com/gyoogle/tech-interview-for-developer/blob/master/Language/%5BJavascript%5D%20ES2015%2B%20%EC%9A%94%EC%95%BD%20%EC%A0%95%EB%A6%AC.md
하지만 이처럼 간단하게 한 줄로 나타내는 것이 가능해졌다. 여러 단계 안의 속성도 count1을 가져오는 것처럼 작성이 가능하다.
의 문장의 소스코드가 이상한 것 같습니다.
첫째로,
```
const candyMachine1 = {
    status: {
        name: 'node',
        count1: 5,
    },
    getCandy1() {
        this.status.count--;
        return this.status.count;
    }
};
 
const { getCandy1, status: { count1 } } = candyMachine1;
```
에서 `candyMachine1.count1` 과 `getCandy1()` 의 key 가 일치하지 않습니다.

둘째로,
위의 코드처럼 비구조화 할당을 한 경우 `this`바인딩이 안 되어 제대로 동작하지 않습니다. (`getCandy1`이)
`this`는 렉시컬 환경에서 동작하지 않습니다. (동적 바인딩이 되어서, 위의 코드처럼 그대로 `getCandy1()` 로 호출하면 브라우저 환경 기준으로 `getCandy1()` 에서는 `this.status.count`를 `window`에서 찾을 것입니다.

**Comment by gyoogle** [comment]
안녕하세요. 자료 확인결과 this 바인딩 부분에서 오류가 있다는 것을 알게 되었습니다. ynifamily3님 말씀처럼 해당 예시 코드에서는 this가 candyMachine1을 가르키지 않는 오류가 있네요. 이슈 감사드립니다:)
