### ISSUE TITLE
원형 큐 구현 관련

### ISSUE THREAD

**Issue by sejnii** [gyoogle/tech-interview-for-developer#114]
안녕하세요! 깔끔한 정리 덕분에 잘 참고하고 있습니다.

data structure/stack&queue 원형 큐 구현 부분에서

```java
public Object deQueue(Object o) {
    
    if(isEmpty()) { 
        return null;
    }
    
    front = (++front) % size;
    Object o = queue[front];
    return o;
}
```

preIndex 변수를 따로 두지 않고, 위와 같이 front가 가리키는 값을 리턴하도록 변경되어야 하지 않을까요?
공백, 포화 상태 구분을 위해 front가 가리키는 값은 빈 값이어야 되기 때문입니다.
확인 부탁 드립니다!

**Comment by gyoogle** [comment]
감사합니다 :) 해당 부분 수정완료했습니다.
