### ISSUE TITLE
Index 설명 오류 제보드립니다. 

### ISSUE THREAD

**Issue by phantasmicmeans** [gyoogle/tech-interview-for-developer#134]
https://github.com/gyoogle/tech-interview-for-developer/blob/master/Computer%20Science/Database/%5BDB%5D%20Index.md

RDB를 대상으로만 인덱스를 설명하고 있는 것 같은데요~ 
인덱스는 rdb, nosql 관계 없이 설명되어야 혼란을 줄일 수 있을 것 같아요

![image](https://user-images.githubusercontent.com/20153890/145540938-0a5cd71b-2562-4a6d-a5b3-c33b2c0a5473.png)

**Comment by gyoogle** [comment]
감사합니다. 해당 부분에 대해 내용 수정하도록 하겠습니다 :)
