### ISSUE TITLE
Typing mistake : Lauguage/[Javascript] Object Prototype.md

### ISSUE THREAD

**Issue by 8471919** [gyoogle/tech-interview-for-developer#173]
https://github.com/gyoogle/tech-interview-for-developer/blob/master/Language/%5BJavasript%5D%20Object%20Prototype.md

Language/[Javasript] Object Prototype.md
위의 경로의 md파일에서 오타를 발견하였습니다.

오타1. A prototype-based language? - 에서 `prototyp object는 method와 property를 상속하는 template object같은 것이다.` 의 맨앞에 prototyp 이 아닌 prototype으로 수정할 필요가 있을 것 같습니다.

오타2. Understanding prototype objects - 에서 `우리는 object instace를 아래와 같이 만들 수 있다.` 에서 instace가 아닌 instance로 수정할 필요가 있어 보입니다.

**Comment by gyoogle** [comment]
감사합니다 적용 완료했습니다.
