### ISSUE TITLE
[제안] github page 호스팅

### ISSUE THREAD

**Issue by ryul99** [gyoogle/tech-interview-for-developer#51]
안녕하세요! 좋은 정리 레포 감사합니다.
자세히 살펴본 것은 아니지만 레포의 게시글들이 마크다운으로 구성되어 있는 듯 한데 마크다운 파일들을 github page로 호스팅하면 좋을 듯 합니다!
레포 설정을 통해서 설정하면 따로 현재 레포의 자료들을 수정하지 않고 호스팅이 가능한 것으로 알고 있습니다.
웹 페이지로 호스팅되면 더 많은 사람들이 접할 수 있을 듯 해서 제안드립니다.

호스팅 방법은 https://pages.github.com/ 에서 project site 선택해서 보실 수 있습니다.

**Comment by kim6394** [comment]
좋은 정보 감사합니다! 시간 여유가 있으면 한번 도전해보도록 하겠습니다!😄
