### ISSUE TITLE
JWT 섹션에 이미지가 깨졌습니다.

### ISSUE THREAD

**Issue by Einere** [gyoogle/tech-interview-for-developer#66]
[JWT 페이지](https://github.com/gyoogle/tech-interview-for-developer/blob/master/Web/JWT(JSON%20Web%20Token).md)
부분의 최하단의 이미지 주소가 잘못되어 깨지는 현상이 발생하네요.
수정이 필요해 보입니다. ☺️

**Comment by gyoogle** [comment]
수정 완료했습니다^^
