### ISSUE TITLE
Java Vector vs List 파트에 의견 드립니다.

### ISSUE THREAD

**Issue by minuk8932** [gyoogle/tech-interview-for-developer#68]
우선 좋은 내용의 많은 자료를 정리해 주신 점에 대해 감사드립니다.

오탈자와 내용관련 이슈 남깁니다. 아래 링크 부분입니다.
(https://github.com/gyoogle/tech-interview-for-developer/blob/master/Interview/Interview%20List.md#%EC%96%B8%EC%96%B4)

삽입 삭제 부분에 Vectro -> Vector 있습니다.

그리고 동기화 부분에서 Vector와 리스트의 설명이 바뀐 것 같네요.
실제로 ArrayList 라이브러리를 열어보시면 아시겠지만 38 ~ 39번째 줄 쯤에 아래와 같이 명시되어 있습니다.
'This class is roughly equivalent to {@code Vector}, except that it is unsynchronized.'
즉, '배열 리스트는 비동기라는 점 외에는 벡터와 같다'라고 쓰여있습니다.
또한 벡터 클래스에서는 동기화 구현이 실제로 되어있는 코드를 확인할 수 있으나 리스트 쪽에선 존재하지 않습니다.
아래는 배열 리스트와 연결리스트 모두에 명시되어있는 내용입니다.
'Note that this implementation is not synchronized.'

또한 반복자의 레벨(?) 항목에서 항목의 의미는 잘 모르겠으나 반드시 순회 해야하는 자료구조는 연결 리스트인 것으로 알고 있습니다.
배열 리스트는 데이터가 추가될 때 내부적으로 배열 복사가 발생해 삽입 삭제 연산이 오래걸리고 참조는 배열과 같이 O(1)이 걸리는 것으로 알고 있습니다.
배열 리스트와 벡터 모두 라이브러리 내용을 보면 객체타입 배열을 기준으로 생성된다는 점과 위에 말씀드린 설명이 그 근거로 말씀드릴 수 있을 것 같습니다. 따라서, 리스트로 묶어서 이야기하기엔 조금 혼동이 있을 것 같습니다.

연결 리스트의 경우 한 노드가 자신의 앞뒤 노드의 위치만 알고 있기 때문에 index 기준으로 get을 하는 방식을 자바에서 제공해주고 있긴하나 말씀하신 내용과 같이 최악의 경우 모두 순회해보아야 하기 때문에 O(N)이 걸리는 것으로 알고 있는데, 연결리스트 내용을 그냥 리스트로 기록해두신 것 같아 보입니다..
혹시 제가 잘못 생각한 부분이 있으면 지적 부탁드립니다. :)

**Comment by gyoogle** [comment]
안녕하세요! 다시 읽어보니 제가 작성을 잘못한 부분이었네요. 확인 감사드립니다! 해당 부분은 다시 정리 후 추후에 추가하도록 하겠습니다 :)
