### ISSUE TITLE
[Design Pattern] 개요 내용 중 Bold 가 제대로 보이지 않습니다.

### ISSUE THREAD

**Issue by Dae-Hwa** [gyoogle/tech-interview-for-developer#69]
좋은 정보들 공유해주셔서 감사합니다.

[[Design Pattern] Overview.md](https://github.com/gyoogle/tech-interview-for-developer/blob/master/Design%20Pattern/%5BDesign%20Pattern%5D%20Overview.md
)

bold처리가 되지않고 
\*\*example\*\* 
와 같이 표시되는 부분이 있습니다.

**Comment by gyoogle** [comment]
해당 부분 업데이트 완료했습니다. 감사드립니다 :)
