### ISSUE TITLE
갑자기 repository 가 추가가 되었는데 제외 부탁드립니다.

### ISSUE THREAD

**Issue by wangun84** [gyoogle/tech-interview-for-developer#94]

**Comment by gyoogle** [comment]
안녕하세요. 아마 레포지토리를 직접 Fork하셔서 추가되신 것 같습니다. 직접 해당 레포지토리에 Settings 들어가시면 레포지토리 삭제가 가능하십니다 :)

**Comment by wangun84** [comment]
제가 GitHub 초보자라 삭제해도 괜찮은지 몰라 주저했었습니다. 
해당 방법으로 진행하겠습니다.

감사합니다.
