### ISSUE TITLE
오탈자 제보드려요

### ISSUE THREAD

**Issue by 00parkjihye** [gyoogle/tech-interview-for-developer#97]
[ETC] Git vs GitHub vs GitLab Flow Add 에서
<img width="500" alt="20201209_224901" src="https://user-images.githubusercontent.com/75290488/101637972-cde4bc80-3a70-11eb-80ff-259b852753f9.png">
3. GitLab Flow 설명중 보안 > 보완이 의미상 맞는것 같아서 제보드립니다

**Comment by gyoogle** [comment]
이슈 감사합니다 :) 해당 내용 수정하겠습니다
